version: '3.1'
services:
  mysql-master:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    volumes:
     - "/data/docker/mysql/master01/data:/var/lib/mysql"
     - "/data/docker/mysql/master01/conf:/etc/mysql/con.d"
     - "/data/docker/mysql/master01/init:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fangming
      MYSQL_DATABASE: mix
      MYSQL_USER: fsmflying
      MYSQL_PASSWORD: fangming
  mysql-slave:
    image: "mysql:latest"
    ports:
     - "3307:3306"
    volumes:
     - "/data/docker/mysql/slave01/data:/var/lib/mysql"
     - "/data/docker/mysql/slave01/conf:/etc/mysql/con.d"
     - "/data/docker/mysql/slave01/init:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fangming
      MYSQL_DATABASE: mix
      MYSQL_USER: fsmflying
      MYSQL_PASSWORD: fangming

    
    
    
