version: '3.1'
services:
  redis-default:
    image: "redis:alpine"
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - "/etc/localtime:/etc/localtime"
  mysql-default:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    volumes:
     - "/data/docker/mysql/data:/var/lib/mysql"
     - "/data/docker/mysql/conf:/etc/mysql/conf.d"
     - "/data/docker/mysql/init:/docker-entrypoint-initdb.d"
     - "/etc/localtime:/etc/localtime"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fangming
      MYSQL_DATABASE: mix
      MYSQL_USER: fsmflying
      MYSQL_PASSWORD: fangming
  rabbitmq-default:
    image: "rabbitmq:3-management"
    ports:
     - "4369:4369"
     - "5671:5671"
     - "5672:5672"
     - "15672:15672"
     - "25672:25672"
    volumes:
     - "/etc/localtime:/etc/localtime"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: fangming

    
    
    
